
services:
  frontend:
    build:
      context: frontend
    ports:
      - 80:8000
    volumes:
      - ./frontend/public/data:/app/public/data

  backend:
    build:
      context: backend
    ports:
      - 8001:8001
    volumes:
      - ./backend/data:/app/data
